version: '3.8'

services:
  postgres-docker:
    image: postgres:15
    container_name: financeiro-db-docker
    ports:
      - "5433:5432" # Porta externa 5433 (para n√£o brigar com o seu Postgres local)
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=financeiro_db
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: